package gui.Panels;

import domain.Score;

import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author firattamur
 */
public class GameOverPanel extends GamePanel {

    private static GameOverPanel panel;


    public static GameOverPanel getInstance(){
        if(panel == null)
            panel = new GameOverPanel();
        return panel;
    }

    /**
     * Creates new form LoginPanel
     */
    public GameOverPanel() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        loginImageField = new javax.swing.JLabel();
        lblGameOver = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 56, 63));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        loginImageField.setIcon(new javax.swing.ImageIcon("Assets/Images/login-image.jpg")); // NOI18N


        lblGameOver.setFont(new java.awt.Font("Phosphate", 0, 48)); // NOI18N
        lblGameOver.setForeground(new java.awt.Color(146, 229, 192));
        lblGameOver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGameOver.setText("Game Over");


        lblScore.setFont(new java.awt.Font("Phosphate", 0, 48)); // NOI18N
        lblScore.setForeground(new java.awt.Color(146, 229, 192));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("Score: "+ Score.getInstance().getCurrentScore());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(loginImageField, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGameOver, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(lblScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginImageField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGameOver)
                .addGap(18, 18, 18)
                .addComponent(lblScore)
                .addGap(66, 66, 66)
                .addGap(123, 123, 123))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblGameOver;
    private javax.swing.JLabel loginImageField;
    // End of variables declaration                   
	@Override
	public void bindPanelListener(JFrame frame) {
		// TODO Auto-generated method stub
		
	}


	@Override
	public void removePanelListener(JFrame frame) {
		// TODO Auto-generated method stub
		
	}

	private boolean isGameWon = false;
	public void setGameWon(boolean bool){
	    this.isGameWon = bool;
        lblGameOver.setText(isGameWon? "You Won":"Game Over");
    }
}
