package gui.Panels;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

import gui.Coordinator;
import gui.ScreenEnum;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author firattamur
 */
public class HelpPanel extends GamePanel {

    /**
     * Creates new form HelpPanel
     */
    public HelpPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        HelpPanel = new javax.swing.JPanel();
        lblHelp = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        helpPowerUps = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblAliens = new javax.swing.JLabel();
        lblSaveLoad = new javax.swing.JLabel();
        lblKeys = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();
        iconLeft = new javax.swing.JLabel();
        lblMagnet = new javax.swing.JLabel();
        lblTaller = new javax.swing.JLabel();
        lblLaserGun = new javax.swing.JLabel();
        lblChemical = new javax.swing.JLabel();
        iconRight = new javax.swing.JLabel();
        iconChemical = new javax.swing.JLabel();
        iconMagnet = new javax.swing.JLabel();
        iconLaser = new javax.swing.JLabel();
        iconTaller = new javax.swing.JLabel();
        lblCooperative = new javax.swing.JLabel();
        lblRepairing = new javax.swing.JLabel();
        lblProtective = new javax.swing.JLabel();
        lblDrunk = new javax.swing.JLabel();
        lblRotateLeft = new javax.swing.JLabel();
        lblRotateRight = new javax.swing.JLabel();
        lblLoad = new javax.swing.JLabel();
        lblPauseResume = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        iconRotateLeft = new javax.swing.JLabel();
        iconLoad = new javax.swing.JLabel();
        iconPauseResume = new javax.swing.JLabel();
        iconSave = new javax.swing.JLabel();
        iconRotateRight = new javax.swing.JLabel();
        iconRepairing = new javax.swing.JLabel();
        iconCooperative = new javax.swing.JLabel();
        iconDrunk = new javax.swing.JLabel();
        iconProtective = new javax.swing.JLabel();

        setBackground(new java.awt.Color(146, 229, 192));
        setPreferredSize(new java.awt.Dimension(750, 500));

        HelpPanel.setBackground(new java.awt.Color(146, 229, 192));
        HelpPanel.setPreferredSize(new java.awt.Dimension(750, 500));

        lblHelp.setFont(new java.awt.Font("Phosphate", 0, 48)); // NOI18N
        lblHelp.setForeground(new java.awt.Color(23, 56, 63));
        lblHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelp.setText("HELP");

        btnMenu.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
        btnMenu.setText("QUIT");

        helpPowerUps.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        helpPowerUps.setForeground(new java.awt.Color(23, 56, 63));
        helpPowerUps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpPowerUps.setText("POWERUPS (Key):");
        helpPowerUps.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        lblRight.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblRight.setForeground(new java.awt.Color(23, 56, 63));
        lblRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRight.setText("RIGHT");

        lblAliens.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblAliens.setForeground(new java.awt.Color(23, 56, 63));
        lblAliens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAliens.setText("ALIENS:");
        lblAliens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        lblSaveLoad.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblSaveLoad.setForeground(new java.awt.Color(23, 56, 63));
        lblSaveLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaveLoad.setText("SAVE/LOAD:");
        lblSaveLoad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        lblKeys.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblKeys.setForeground(new java.awt.Color(23, 56, 63));
        lblKeys.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeys.setText("KEYS:");
        lblKeys.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        lblLeft.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblLeft.setForeground(new java.awt.Color(23, 56, 63));
        lblLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLeft.setText("LEFT");

        iconLeft.setIcon(new ImageIcon(new ImageIcon("Assets/Images/HelpScreen/key-left.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        lblMagnet.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblMagnet.setForeground(new java.awt.Color(23, 56, 63));
        lblMagnet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnet.setText("MAgnet(M)");

        lblTaller.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblTaller.setForeground(new java.awt.Color(23, 56, 63));
        lblTaller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaller.setText("TalleR PADDLE(T)");

        lblLaserGun.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblLaserGun.setForeground(new java.awt.Color(23, 56, 63));
        lblLaserGun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLaserGun.setText("LASER GUN(SPACE)");

        lblChemical.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblChemical.setForeground(new java.awt.Color(23, 56, 63));
        lblChemical.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChemical.setText("CHEMICAL BALL(C)");

        iconRight.setIcon(new ImageIcon(new ImageIcon("Assets/Images/HelpScreen/key-right.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconChemical.setIcon(new ImageIcon(new ImageIcon("Assets/Images/flask.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconMagnet.setIcon(new ImageIcon(new ImageIcon("Assets/Images/magnetism.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconLaser.setIcon(new ImageIcon(new ImageIcon("Assets/Images/laser-pen.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconTaller.setIcon(new ImageIcon(new ImageIcon("Assets/Images/expand.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        lblCooperative.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblCooperative.setForeground(new java.awt.Color(23, 56, 63));
        lblCooperative.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCooperative.setText("COOPERATIVE");

        lblRepairing.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblRepairing.setForeground(new java.awt.Color(23, 56, 63));
        lblRepairing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRepairing.setText("REPAIRING");

        lblProtective.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblProtective.setForeground(new java.awt.Color(23, 56, 63));
        lblProtective.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProtective.setText("PROTECTIVE");

        lblDrunk.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblDrunk.setForeground(new java.awt.Color(23, 56, 63));
        lblDrunk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrunk.setText("DRUNK");

        lblRotateLeft.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblRotateLeft.setForeground(new java.awt.Color(23, 56, 63));
        lblRotateLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRotateLeft.setText("ROTATE-LEFT");

        lblRotateRight.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblRotateRight.setForeground(new java.awt.Color(23, 56, 63));
        lblRotateRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRotateRight.setText("ROTATE-RIGHT");

        lblLoad.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblLoad.setForeground(new java.awt.Color(23, 56, 63));
        lblLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoad.setText("LOAD");

        lblPauseResume.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblPauseResume.setForeground(new java.awt.Color(23, 56, 63));
        lblPauseResume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPauseResume.setText("PAUSE/RESUME");

        lblSave.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        lblSave.setForeground(new java.awt.Color(23, 56, 63));
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setText("SAVE");

        iconRotateLeft.setIcon(new ImageIcon(new ImageIcon("Assets/Images/HelpScreen/key-A.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconLoad.setIcon(new ImageIcon(new ImageIcon("Assets/Images/HelpScreen/key-L.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconPauseResume.setIcon(new ImageIcon(new ImageIcon("Assets/Images/HelpScreen/key-P.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconSave.setIcon(new ImageIcon(new ImageIcon("Assets/Images/HelpScreen/key-S.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconRotateRight.setIcon(new ImageIcon(new ImageIcon("Assets/Images/HelpScreen/key-D.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconRepairing.setIcon(new ImageIcon(new ImageIcon("Assets/Images/repairing.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconCooperative.setIcon(new ImageIcon(new ImageIcon("Assets/Images/cooperative.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconDrunk.setIcon(new ImageIcon(new ImageIcon("Assets/Images/drunk.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        iconProtective.setIcon(new ImageIcon(new ImageIcon("Assets/Images/protective.png").getImage().getScaledInstance(edgeLength, edgeLength, Image.SCALE_DEFAULT)));

        javax.swing.GroupLayout HelpPanelLayout = new javax.swing.GroupLayout(HelpPanel);
        HelpPanel.setLayout(HelpPanelLayout);
        HelpPanelLayout.setHorizontalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPanelLayout.createSequentialGroup()
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HelpPanelLayout.createSequentialGroup()
                                .addComponent(lblKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204)
                                .addComponent(lblHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HelpPanelLayout.createSequentialGroup()
                                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HelpPanelLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(iconPauseResume)
                                        .addGap(96, 96, 96)
                                        .addComponent(iconSave)
                                        .addGap(73, 73, 73)
                                        .addComponent(iconLoad))
                                    .addGroup(HelpPanelLayout.createSequentialGroup()
                                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iconLeft)
                                            .addComponent(lblLeft))
                                        .addGap(33, 33, 33)
                                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRight)
                                            .addComponent(iconRight))
                                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(HelpPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lblRotateLeft)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblRotateRight))
                                            .addGroup(HelpPanelLayout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(iconRotateLeft)
                                                .addGap(84, 84, 84)
                                                .addComponent(iconRotateRight))))
                                    .addComponent(helpPowerUps, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(HelpPanelLayout.createSequentialGroup()
                                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(HelpPanelLayout.createSequentialGroup()
                                                .addComponent(lblRepairing)
                                                .addGap(32, 32, 32)
                                                .addComponent(lblCooperative))
                                            .addComponent(lblSaveLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)
                                        .addComponent(lblProtective)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblDrunk))
                                    .addComponent(lblAliens, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(HelpPanelLayout.createSequentialGroup()
                                        .addComponent(lblPauseResume)
                                        .addGap(48, 48, 48)
                                        .addComponent(lblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(lblLoad))
                                    .addGroup(HelpPanelLayout.createSequentialGroup()
                                        .addComponent(lblMagnet)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTaller)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblChemical)
                                        .addGap(27, 27, 27)
                                        .addComponent(lblLaserGun)))
                                .addGap(0, 134, Short.MAX_VALUE))))
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(iconMagnet)
                        .addGap(88, 88, 88)
                        .addComponent(iconTaller)
                        .addGap(126, 126, 126)
                        .addComponent(iconChemical)
                        .addGap(142, 142, 142)
                        .addComponent(iconLaser)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(HelpPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(iconRepairing)
                .addGap(97, 97, 97)
                .addComponent(iconCooperative)
                .addGap(122, 122, 122)
                .addComponent(iconProtective)
                .addGap(73, 73, 73)
                .addComponent(iconDrunk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HelpPanelLayout.setVerticalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPanelLayout.createSequentialGroup()
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(HelpPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconLeft)
                    .addComponent(iconRight)
                    .addComponent(iconRotateLeft)
                    .addComponent(iconRotateRight))
                .addGap(13, 13, 13)
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeft)
                    .addComponent(lblRight)
                    .addComponent(lblRotateLeft)
                    .addComponent(lblRotateRight))
                .addGap(18, 18, 18)
                .addComponent(helpPowerUps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iconTaller)
                        .addComponent(iconChemical)
                        .addComponent(iconMagnet, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(iconLaser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMagnet)
                    .addComponent(lblTaller)
                    .addComponent(lblLaserGun)
                    .addComponent(lblChemical))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAliens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconRepairing)
                            .addComponent(iconProtective)
                            .addComponent(iconDrunk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCooperative)
                            .addComponent(lblRepairing)
                            .addComponent(lblProtective)
                            .addComponent(lblDrunk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaveLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconLoad)
                            .addComponent(iconPauseResume)
                            .addComponent(iconSave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPauseResume)
                            .addComponent(lblSave)
                            .addComponent(lblLoad))
                        .addGap(25, 25, 25))
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addComponent(iconCooperative)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 499, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JPanel HelpPanel;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel helpPowerUps;
    private javax.swing.JLabel iconChemical;
    private javax.swing.JLabel iconCooperative;
    private javax.swing.JLabel iconDrunk;
    private javax.swing.JLabel iconLaser;
    private javax.swing.JLabel iconLeft;
    private javax.swing.JLabel iconLoad;
    private javax.swing.JLabel iconMagnet;
    private javax.swing.JLabel iconPauseResume;
    private javax.swing.JLabel iconProtective;
    private javax.swing.JLabel iconRepairing;
    private javax.swing.JLabel iconRight;
    private javax.swing.JLabel iconRotateLeft;
    private javax.swing.JLabel iconRotateRight;
    private javax.swing.JLabel iconSave;
    private javax.swing.JLabel iconTaller;
    private javax.swing.JLabel lblAliens;
    private javax.swing.JLabel lblChemical;
    private javax.swing.JLabel lblCooperative;
    private javax.swing.JLabel lblDrunk;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblKeys;
    private javax.swing.JLabel lblLaserGun;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblLoad;
    private javax.swing.JLabel lblMagnet;
    private javax.swing.JLabel lblPauseResume;
    private javax.swing.JLabel lblProtective;
    private javax.swing.JLabel lblRepairing;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblRotateLeft;
    private javax.swing.JLabel lblRotateRight;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblSaveLoad;
    private javax.swing.JLabel lblTaller;
    // End of variables declaration 
    
    private int edgeLength = 32;
    
    
    private PanelListener listener = new PanelListener();
    
    
    private class PanelListener implements ActionListener {

		public PanelListener(){

		}

		@Override
		public void actionPerformed(ActionEvent actionEvent) {
			if(actionEvent.getSource().equals(btnMenu)){
				Coordinator.getInstance().openScreen(ScreenEnum.MAIN);
			}

		}

	}


    @Override
	public void bindPanelListener(JFrame frame) {
    	btnMenu.addActionListener(listener);
	}

	@Override
	public void removePanelListener(JFrame frame) {
		btnMenu.removeActionListener(listener);
	}

     
}

