/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Panels;

import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;

import Services.Database.DatabaseStrategy;
import domain.Controllers.MainScreenController;

/**
 *
 * @author firattamur
 */
@SuppressWarnings("serial")
public class MainPanel extends GamePanel {

    /**
     * Creates new form LoginPanel
     */
    public MainPanel() {
        initComponents();
    }
    
    public static void main(String[] args) {
        
        JFrame frame = new JFrame();
        frame.setVisible(true);
        frame.setSize(750, 500);
        frame.add(new LoginPanel());
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        loginImageField = new javax.swing.JLabel();
        btnLoadGame = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();

        setBackground(new java.awt.Color(23, 56, 63));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        loginImageField.setIcon(new javax.swing.ImageIcon("Assets/Images/login-image.jpg")); // NOI18N

        btnLoadGame.setBackground(new java.awt.Color(146, 229, 192));
        btnLoadGame.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        btnLoadGame.setForeground(new java.awt.Color(23, 56, 63));
        btnLoadGame.setText("Load game");
        btnLoadGame.setEnabled(DatabaseStrategy.getInstance().userHasSaveFile());

        btnHelp.setBackground(new java.awt.Color(146, 229, 192));
        btnHelp.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(23, 56, 63));
        btnHelp.setText("help");
        
       
        btnNewGame.setBackground(new java.awt.Color(146, 229, 192));
        btnNewGame.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        btnNewGame.setForeground(new java.awt.Color(23, 56, 63));
        btnNewGame.setText("New Game");
       
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(loginImageField, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginImageField, javax.swing.GroupLayout.PREFERRED_SIZE, 498, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

                                    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLoadGame;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel loginImageField;
    // End of variables declaration                   
    
    private PanelListener listener = new PanelListener();
    // End of variables declaration   
    
    @Override
	public void bindPanelListener(JFrame frame) {
		btnHelp.addActionListener(listener);
		btnLoadGame.addActionListener(listener);
		btnNewGame.addActionListener(listener);
	}

	@Override
	public void removePanelListener(JFrame frame) {
		// TODO Auto-generated method stub
		btnHelp.removeActionListener(listener);
		btnLoadGame.removeActionListener(listener);
		btnNewGame.removeActionListener(listener);
	}
	
	private class PanelListener implements ActionListener {

		public PanelListener(){

		}

		@Override
		public void actionPerformed(ActionEvent actionEvent) {
			if(actionEvent.getSource().equals(btnNewGame))
				MainScreenController.getInstance().newGame();
			if(actionEvent.getSource().equals(btnLoadGame)){
				MainScreenController.getInstance().loadGame();
			}
			if(actionEvent.getSource().equals(btnHelp))
				MainScreenController.getInstance().help();
		}

	}
	
}

